# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-06 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170503_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u0442\u0435\u0433\u0438')),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', related_query_name='keyword', to='article.Keywords', verbose_name='\u0442\u0435\u0433\u0438'),
        ),
    ]
